# 修改日期2025-01-23
# 新增Table trace_dataset_config
# 新增欄位tracing在datasets的Table

"""change workflow_runs.total_tokens to bigint

Revision ID: a91b476a53de
Revises: 923752d42eb6
Create Date: 2025-01-01 20:00:01.207369

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91b476a53de'
down_revision = '923752d42eb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_dataset_config',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('dataset_id', models.types.StringUUID(), nullable=False),
    sa.Column('tracing_provider', sa.String(length=255), nullable=True),
    sa.Column('tracing_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracing_dataset_config_pkey')
    )
    with op.batch_alter_table('trace_dataset_config', schema=None) as batch_op:
        batch_op.create_index('trace_dataset_config_dataset_id_idx', ['dataset_id'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracing', sa.Text(), nullable=True))
        
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('total_tokens',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('tracing')

    with op.batch_alter_table('trace_dataset_config', schema=None) as batch_op:
        batch_op.drop_index('trace_dataset_config_dataset_id_idx')
        
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('total_tokens',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        
    op.drop_table('trace_dataset_config')

    # ### end Alembic commands ###
