"""Add database tracing config

Revision ID: 77e34d269b57
Revises: cf8f4fc45278
Create Date: 2025-01-08 02:01:16.773710

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e34d269b57'
down_revision = 'cf8f4fc45278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trace_dataset_config',
    sa.Column('id', models.types.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('dataset_id', models.types.StringUUID(), nullable=False),
    sa.Column('tracing_provider', sa.String(length=255), nullable=True),
    sa.Column('tracing_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tracing_dataset_config_pkey')
    )
    with op.batch_alter_table('trace_dataset_config', schema=None) as batch_op:
        batch_op.create_index('trace_dataset_config_dataset_id_idx', ['dataset_id'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracing', sa.Text(), nullable=True))

    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('outputs',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.alter_column('outputs',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('tracing')

    with op.batch_alter_table('trace_dataset_config', schema=None) as batch_op:
        batch_op.drop_index('trace_dataset_config_dataset_id_idx')

    op.drop_table('trace_dataset_config')
    # ### end Alembic commands ###
